# General parameters
env-id: ["SlateBorNoInf-ucar-v0"] #, "SlateBorNoInf-ucar-v0", "SlateBorNoInf-utloi-worp-v0", "SlateBorNoInf-utloi-wrp-v0"]
seed: 2023 #[2023, 2024, 2025]
agent: hac
observable: False

# Training
total-timesteps: 500000
val-interval: 50000
n-val-episodes: 25
buffer-size: 1000000
batch-size: 32

# Agent
n-updates: 1
policy-frequency: 1
hyper-frequency: 1
behavior-frequency: 1
q-lr: 0.001 # Range: 0.001 0.0001, default: 0.001
policy-lr: 0.0003 # Range: 0.0003 0.00003, default: 0.0003
behavior-lr: 0.00003 # Range: 0.00003 0.000003, default: 0.00003
tau: 0.05 # Range: 0.5 0.05, default: 0.05
target-network-frequency: 1
target-actor-frequency: 1
hidden-size: 256
reparam-std: 0.1 # Range: 1 0.1 0.01 0.001, default: 0.1
hyper-weight: 0.1 # Range: 1 0.1 0.01, default: 0.1
latent-dim: 32 # Range: 64 32 16, default: 32; Unused if raw-features = True
latent-low: 0.0 # Use -1 if raw-features = False
latent-high: 1.0
raw-features: True

# State encoder
state-encoder: gru # gru or transformer
state-dim: 32  # Only for POMDP
sampled-seq-len: 10
#item-dim-se: 32 # Only for Transformer

# Misc
info: hac_ideal_pomdp
track: tensorboard #wandb
#wandb-entity: SlateRL
#wandb-project-name: SlateRL
