# General parameters
env-id: ["SlateRerank-Bored-v0"] #, "SingleItemDynamic-v0"]
seed: [2705, 3751, 4685, 3688, 6383]
agent: topk_reinforce
observable: True

# Training
total-timesteps: 500000
val-interval: 50000
n-val-episodes: 25
buffer-size: 10

# Agent
policy-frequency: 1
policy-lr: 0.0003
gamma: 0.8
hidden-size: 256

# Misc
info: topk_reinforce_obs
track: wandb #wandb
wandb-project-name: SlateRL
