# General parameters
env-id: ["SlateTopK-Bored-v0"] #, "SingleItemDynamic-v0"]
seed: [2023, 2024, 2025]
agent: topk_reinforce
observable: True

# Training
total-timesteps: 100000
val-interval: 50000
n-val-episodes: 25
buffer-size: 100

# Agent
policy-frequency: 1
policy-lr: 0.0003
gamma: 0.8
hidden-size: 256

# Misc
info: topk_reinforce_obs
track: wandb #wandb
wandb-project-name: SlateRL
